// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================
/* Optimization type */
#define RO 			0    // Resource Optimized (8-pixel implementation)
#define NO 			1	 // Normal Operation (1-pixel implementation)

// defining these creates issues with the cvtColor libraries so we ain't needing them
// #define RGBA 1
// #define GRAY 0
/* Interpolation type*/
#define INTERPOLATION	1
// 0 - Nearest Neighbor Interpolation
// 1 - Bilinear Interpolation
// 2 - AREA Interpolation

// our imput image is around 1280 x 720
/* Max image Dimensions */
#define WIDTH 			1280	// Maximum  image width
#define HEIGHT 			720   	// Maximum image height


